### ISSUE TITLE
AttributeError: Can't find attribute SvgDocumentElement.viewbox_height

### ISSUE THREAD

**Issue by slippers** [johnbeard/inkscape-label-guides#6]
Installed with the make tool.  appears in the extensions.  dialog and python runs.

getting this error

Inkscape 1.1.2 (0a00cf5339, 2022-02-04)

```
Traceback (most recent call last):
  File "/home/kirk/.config/inkscape/extensions/label_guides.py", line 606, in <module>
    LabelGuides().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "/home/kirk/.config/inkscape/extensions/label_guides.py", line 586, in effect
    self._draw_label_guides(self.document, label_opts, 0,
  File "/home/kirk/.config/inkscape/extensions/label_guides.py", line 479, in _draw_label_guides
    add_SVG_guide(0, self.svg.viewbox_height - g, 'horz', colour, nv)
  File "/usr/share/inkscape/extensions/inkex/elements/_base.py", line 165, in __getattr__
    raise AttributeError(f"Can't find attribute {self.typename}.{name}")
AttributeError: Can't find attribute SvgDocumentElement.viewbox_height
```

**Comment by slippers** [comment]
Was on the wrong version of inkscape.

An upgrade from 1.1.2 to 1.3.2  fixed this issue. 
https://inkscape.org/release/1.2/gnulinux/

after looking up the method svg.viewbox_height i could see that there were changes

[viewbox](https://inkscape.gitlab.io/extensions/documentation/source/inkex.elements._svg.html?highlight=svg%20viewbox_height#inkex.elements._svg.SvgDocumentElement.viewbox_height)

didn't see an established way of version checking in the extension.
